version: '3.7'
services:
  indexer:
    build:
      context: .
      dockerfile: build/indexer/Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app
      - gocache:/gocache
    command: ['go', 'run', 'cmd/indexer/main.go']
  monitor:
    build:
      context: .
      dockerfile: build/indexer/Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app
      - gocache:/gocache
    command: ['go', 'run', 'cmd/monitor/main.go']
volumes:
  gocache: