apiVersion: v1
kind: Service
metadata:
  name: {{ include "nudgle.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nudgle.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nudgle.selectorLabels" . | nindent 4 }}
